# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: deea31b88df5e7ebc8d8adf2f78c6087c0760130799ebecf76bb63f1f9ae40638768fe6a5aed0145772afbd7d7952b5b271a3b746eca84f4052332c46a1c10bd

test:
  secret_key_base: aa154e5ace4f0aa2776474383de905796947bd5f705e5ceac5a4420c48ee4349df9d82bc5b588137ae74e2d3ca9c72c0a21cd23487400f98ec88200a8a4bb384

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
